# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ] 
standalone_tags:
  [
    {id: 0, size: 0.8, name: Apriltag36_11_00000},
    {id: 1, size: 0.8, name: Apriltag36_11_00001},
    {id: 2, size: 0.8, name: Apriltag36_11_00002},
    {id: 3, size: 0.8, name: Apriltag36_11_00003},
    {id: 4, size: 0.8, name: Apriltag36_11_00004},
    {id: 5, size: 0.8, name: Apriltag36_11_00005},
    {id: 6, size: 0.8, name: Apriltag36_11_00006},
    {id: 7, size: 0.8, name: Apriltag36_11_00007},
    {id: 8, size: 0.8, name: Apriltag36_11_00008},
    {id: 9, size: 0.8, name: Apriltag36_11_00009},
    {id: 10, size: 0.8, name: Apriltag36_11_000010},
    {id: 11, size: 0.8, name: Apriltag36_11_000011}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
